version: 2.1

jobs:
  build:
    machine:
      environment:
        APPLICATION_ENV: testing

        php:
          version: 5.5.21

        node:
          version: 6.10.3

        ruby:
          version: 2.0.0-p648
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor